server:
  port: 9004
  ssl:
    enabled: false
    
logging:
  config: classpath:logback.xml
           
spring:
  application:
    name: Nara-Market
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      
  profiles:
    active: local
    
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

default.datasource:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://nara-market-dev.cjuu688y685g.ap-northeast-2.rds.amazonaws.com:5432/postgres
      username: postgres
      password: dnekdxkdxkd1234
      hikari:
        auto-commit: false
        connection-test-query: SELECT 1
        minimum-idle: 10
        maximum-pool-size: 50

kainos:
  web:
    cors:
      credentials: true
  ## http response body format 사용
  response:
    body:
      format:
        enabled: true
  ## http security 로그인 체크 기능
  security:
    enabled: true
    sameSite: None
    secure: true
    httpOnly: true
    url:
      include: /api/*
      exclude: /open/*
    ## JWT 사용
  session:
    secretKey: aYEFtKMCn0xCg5caH1nnFuHfdAB0lBOvdonxq80VqOGNnG6QcyagXWOLrUdqJnzexUXYceMhGNFNYsA6rblSibUEh0yRsJ3XO1um1iMdoekOPzj4zKlokcu9TxTbz5DHYVLkqX3q9JrLgbLZFXD8ynOHfRHRL5Ge64iFZBVm9X517fwZrNornOmK2L7hUz10SgZpxAz6
    accessExpireTime: 3600000 #1시간 Access Token
    refreshExpireTime: 10800000 #3시간 Refresh Token
  
#  querydsl:
#    native:
#      locations: classpath:/kainos/web/sample/**/query/*.xml
#      autoreload:
#        interval: 2000
            
  message:
    enabled: true
    path: classpath:/message/*.yml ## 파일 사용할 경우
    